### ISSUE TITLE
Fix "npm run build" problem

### ISSUE THREAD

**Issue by volkcloud** [near/near-sdk-js-template-project#9]
Hello, 
I had problem building this template. Running "npm run build"(as in readme), process file with "near-sdk: not found".

If i replace, in package.json, "build: near-sdk build" with "build: near-sdk**-js** build" it works.

Where my mistake?
Using ubuntu desktop 22LTS.
Thanks

**Comment by ailisp** [comment]
Hi @volkcloud , you are correct, it's a bug in our side and fixed in #7
